services:

  web:
    container_name: docker-test-web-dev
    build:
      context: ./web
      target: builder
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    user: root
    command: sh -c "yarn install && yarn dev -p 8080"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 8080
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_started
    networks:
      - backend

  api:
    container_name: docker-test-nest-api-dev
    build:
      context: ./api
      target: builder
    user: root
    command: sh -c "yarn install && yarn start:dev"
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:

volumes:
  api_node_modules:
  web_node_modules:
